apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIxMDUwNTE5MTYzMFoXDTMxMDUwNDE5MTYzMFowFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOpR
    rQK4cnbqHihJLmhJXlZSvGSszRrZ8rPFl0mzv4fUfLrf7ULTdN5xWF/jMVqP/r0e
    29TV4KI/Y38Ph+HfA+nm8TaCQbq/pHaCtnbOl+6VN6jB0+uLxr6gEqX13ZL1P3tm
    T3gZnzZaWFmOfg3HPNx10K0YSWwEoDuwjUpD9w6QNwsZNaMrvWyEmxXJQ6oluF33
    af+Kug0TqsZRAVm0zs9LPbl+Vj64f0/Lg/OAteoCcIK9Eal4qT6XqOpCkC0kEPTQ
    /pnBhcvxWkvZSoD6S4C+mN28cqT+cCZnojaOzub7Wb5FQX/3+Z8C4t6kAiVVaAF9
    QEjXGKY1mtCH5LqU+jUCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBTUD/9KBuy/yjxGHlakru2eUmpi4DANBgkqhkiG9w0BAQsFAAOCAQEARQWUlZut
    KKlFX1f5XGJ02ZSiS+UVt+ajJRcXpsOz5yp43BEdU6NshSD1Wm3jj3QNmOw7s0F6
    ++QipzN7ZP+acyOe+cy64M130Z1j0yFwDvzwOHExChk1ZQoRCQGhL3ylA7m3lPYD
    ZBK1Pv3DwMhpmAp0NZ/1w5FLJ5AZiT9O/FNTE0TtsBqe5BRultAB2fDU+3WdvCVH
    qDCcOh471RA86cXTQb3RtQ+fZk7OqBbfW3JphRX8wVmRcy9Rp04rNmYSpfTZjCHd
    vVTaN22qcH1vmzDRDJcZhOwksxiVFyhn8BebI9rBVBz3UFPAgkEju6ZQqgOLkdON
    iNq9Vs2jJxAeWQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-31T16:11:19Z"
  name: kube-root-ca.crt
  namespace: guestbook
